export interface Grant {
  id: string;
  name: string;
  provider: string;
  amount: string;
  deadline: string;
  category: string;
  location: string;
  image: string;
  description: string;
  eligibility: string[];
  applicationLink: string;
  tags: string[];
}

export const grantsData: Grant[] = [
  {
    id: "1",
    name: "1517 Medici Project",
    provider: "1517 Fund",
    amount: "$1,000",
    deadline: "Rolling",
    category: "Youth",
    location: "Global",
    image: "/images/MercatusCenter.jpg",
    description: "High school, college students, and dropouts to launch projects to make humanity better",
    eligibility: ["High school students", "College students", "Dropouts", "Project-focused"],
    applicationLink: "https://www.1517fund.com/medici-project",
    tags: ["Youth", "Innovation", "Projects"]
  },
  {
    id: "2",
    name: "776 Fellowship",
    provider: "776 Foundation",
    amount: "$100,000",
    deadline: "March 15, 2024",
    category: "Climate",
    location: "Global",
    image: "/images/MercatusCenter.jpg",
    description: "Young people tackling climate change",
    eligibility: ["Young innovators", "Climate-focused projects", "Scalable solutions"],
    applicationLink: "https://www.776.org/",
    tags: ["Climate", "Youth", "Environment"]
  },
  {
    id: "3",
    name: "Activate Fellowship",
    provider: "Activate Global Inc.",
    amount: "$275,000",
    deadline: "April 1, 2024",
    category: "Science",
    location: "United States",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "We empower scientists to reinvent the world",
    eligibility: ["PhD scientists", "Deep tech innovation", "Commercialization ready"],
    applicationLink: "https://www.activate.org/the-fellowship",
    tags: ["Science", "Deep Tech", "Fellowship"]
  },
  {
    id: "4",
    name: "Antikythera Studio",
    provider: "Berggruen Institute",
    amount: "$5,000",
    deadline: "May 20, 2024",
    category: "Interdisciplinary",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Will select 12-18 interdisciplinary, full time Studio Researchers–including engineers, designers, scientists, philosophers, writers and technologists–to develop speculative prototypes & propositions",
    eligibility: ["Interdisciplinary researchers", "Full-time commitment", "Engineers, designers, scientists, philosophers, writers, technologists"],
    applicationLink: "https://antikythera.org/studios",
    tags: ["Interdisciplinary", "Research", "Innovation"]
  },
  {
    id: "5",
    name: "Awesome Foundation",
    provider: "Awesome Foundation",
    amount: "$1,000",
    deadline: "Rolling",
    category: "Community",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Distributes $1,000 grants, no strings attached, to projects and their creators",
    eligibility: ["Any creative project", "Community-focused", "No strings attached"],
    applicationLink: "https://www.awesomefoundation.org/en",
    tags: ["Community", "Micro-grant", "Creative"]
  },
  {
    id: "6",
    name: "Brains",
    provider: "Spec.tech",
    amount: "No funding",
    deadline: "Rolling",
    category: "Research Programs",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Like YCombinator for coordinated research programs. No funding, but 13 week training program with 2 in-person events. On Demo Day, pitch your program to partners interested in funding research programs or hiring research leaders",
    eligibility: ["Research program coordinators", "13-week commitment", "Demo day pitch"],
    applicationLink: "https://spec.tech/brains",
    tags: ["Research", "Training", "Accelerator"]
  },
  {
    id: "7",
    name: "The Civic Innovators Fellowship",
    provider: "Civics Unplugged",
    amount: "Fellowship",
    deadline: "June 1, 2024",
    category: "Civic Innovation",
    location: "United States",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Fellowship program for civic innovators working to strengthen democracy and community engagement",
    eligibility: ["Civic innovators", "Community organizers", "Democracy advocates"],
    applicationLink: "https://www.civicsunplugged.org/",
    tags: ["Civic", "Fellowship", "Democracy"]
  },
  {
    id: "8",
    name: "Cosmos",
    provider: "Cosmos Institute",
    amount: "$1,000 - $10,000",
    deadline: "Rolling",
    category: "Philosophy & Tech",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Cosmos Ventures: fast grants for prototyping in the philosophy of technology. Cosmos Fellowship: grants supporting the best builders and thinkers in Philosophy/Tech",
    eligibility: ["Scientific researchers", "Philosophy/Tech builders", "Prototype-focused"],
    applicationLink: "https://cosmosinstitute.substack.com",
    tags: ["Philosophy", "Technology", "Research"]
  },
  {
    id: "9",
    name: "DojoGrants",
    provider: "Nucleate Dojo / Intuitive Foundation",
    amount: "Up to $8,000",
    deadline: "Rolling",
    category: "Life Sciences",
    location: "United States",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "The first institution-agnostic, year-round life sciences research funding program for undergrads",
    eligibility: ["Undergraduate students", "Life sciences research", "Any institution"],
    applicationLink: "https://dojo.nucleate.xyz/dojogrants",
    tags: ["Life Sciences", "Undergrad", "Research"]
  },
  {
    id: "10",
    name: "EA Infrastructure Funds",
    provider: "Effective Ventures Foundation",
    amount: "$5,000 - $200,000",
    deadline: "Rolling",
    category: "Effective Altruism",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Project you think will improve the world, and it seems like a good fit for one of our funds - Animal Welfare / EA causes",
    eligibility: ["EA-aligned projects", "Global impact", "Evidence-based approach"],
    applicationLink: "https://funds.effectivealtruism.org/apply-for-funding",
    tags: ["EA", "Impact", "Global Health"]
  },
  {
    id: "11",
    name: "EA Animal Welfare Fund",
    provider: "Effective Ventures Foundation",
    amount: "$1,000 - $500,000",
    deadline: "Rolling",
    category: "Animal Welfare",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Aims to effectively improve the well-being of nonhuman animals",
    eligibility: ["Animal welfare focus", "Evidence-based", "Scalable impact"],
    applicationLink: "https://funds.effectivealtruism.org/apply-for-funding",
    tags: ["Animal Welfare", "EA", "Impact"]
  },
  {
    id: "12",
    name: "Edge City Fellowship",
    provider: "Gary Sheng",
    amount: "Fellowship",
    deadline: "March 30, 2024",
    category: "Innovation",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Empowers young innovators across domains critical for human flourishing via a full-ride to a month-long immersive co-living experience",
    eligibility: ["Young innovators", "Month-long commitment", "Human flourishing focus"],
    applicationLink: "https://edgecity.notion.site/",
    tags: ["Fellowship", "Innovation", "Co-living"]
  },
  {
    id: "13",
    name: "Emergent Ventures",
    provider: "Mercatus Center",
    amount: "$5,000+",
    deadline: "Rolling",
    category: "Innovation",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Support entrepreneurs with highly scalable, 'zero to one' ideas for meaningfully improving society",
    eligibility: ["Innovative entrepreneurs", "Scalable ideas", "Social impact"],
    applicationLink: "https://www.mercatus.org/emergent-ventures",
    tags: ["Innovation", "Entrepreneurship", "Impact"]
  },
  {
    id: "14",
    name: "Emergent Ventures India",
    provider: "Mercatus Center",
    amount: "$5,000+",
    deadline: "Rolling",
    category: "Innovation",
    location: "India",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Support entrepreneurs with highly scalable, 'zero to one' ideas for meaningfully improving society from India",
    eligibility: ["Indian entrepreneurs", "Scalable ideas", "Social impact"],
    applicationLink: "https://www.mercatus.org/emergent-ventures",
    tags: ["Innovation", "India", "Entrepreneurship"]
  },
  {
    id: "15",
    name: "Foresight Fellowship",
    provider: "Foresight Institute",
    amount: "Fellowship",
    deadline: "April 15, 2024",
    category: "Technology",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Fellowship program focused on transformative technologies and long-term thinking",
    eligibility: ["Tech innovators", "Long-term thinking", "Transformative tech"],
    applicationLink: "https://foresight.org/foresight-fellowships/",
    tags: ["Technology", "Fellowship", "Future"]
  },
  {
    id: "16",
    name: "Gitcoin Grants",
    provider: "Gitcoin",
    amount: "Varies",
    deadline: "Rolling",
    category: "Public Goods",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Discover and Fund Public Goods",
    eligibility: ["Public goods projects", "Open source", "Community-driven"],
    applicationLink: "https://gitcoin.co/grants",
    tags: ["Crypto", "Public Goods", "Open Source"]
  },
  {
    id: "17",
    name: "Henry Arnhold Fellowship",
    provider: "Mulago Foundation",
    amount: "$100,000",
    deadline: "May 1, 2024",
    category: "Conservation",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "We find leaders with promising conservation and climate solutions and help them to design and deliver them at scale",
    eligibility: ["Conservation leaders", "Climate solutions", "Scalable impact"],
    applicationLink: "https://www.mulagofoundation.org/henry-fellows-program",
    tags: ["Conservation", "Climate", "Fellowship"]
  },
  {
    id: "18",
    name: "Inflection Grants",
    provider: "Cyan Banister",
    amount: "$2,000",
    deadline: "Rolling",
    category: "Youth",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Under 25 grants for ambitious young builders",
    eligibility: ["Under 25 years old", "Ambitious projects", "Self-driven"],
    applicationLink: "https://www.inflectiongrants.com/",
    tags: ["Youth", "Micro-grant", "Innovation"]
  },
  {
    id: "19",
    name: "Longevity Fellowship",
    provider: "LessDeath Inc",
    amount: "Fellowship",
    deadline: "June 15, 2024",
    category: "Longevity",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "The Longevity Biotech Fellowship Program for new members is 12-weeks of orientation, connection, and mentorship to equip people with the right context and opportunities to make an impact on aging",
    eligibility: ["Longevity biotech focus", "12-week commitment", "Membership fee $699-$1299"],
    applicationLink: "https://www.longbiofellowship.org/",
    tags: ["Longevity", "Biotech", "Fellowship"]
  },
  {
    id: "20",
    name: "Magnificent Grants",
    provider: "Hummingbird Ventures",
    amount: "$10,000+",
    deadline: "July 1, 2024",
    category: "Youth",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "10 exceptional talented pioneers, Under 25yrs old, will receive a $10k+ grant to bypass obstacles and fight the status quo",
    eligibility: ["Under 25 years old", "Exceptional talent", "Status quo challengers"],
    applicationLink: "https://magnificentgrants.com",
    tags: ["Youth", "Innovation", "Pioneers"]
  },
  {
    id: "21",
    name: "Eclipse Grants",
    provider: "Molly Mielke",
    amount: "$5,000",
    deadline: "Rolling",
    category: "Venture",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Early-stage-focused venture capital firm that aims to increase the agency of extraordinary individuals using both investment dollars and grants. Under 25",
    eligibility: ["Under 25 years old", "Early-stage projects", "Extraordinary individuals"],
    applicationLink: "https://newscience.org/grants-and-fellowships/",
    tags: ["Youth", "Venture", "Early-stage"]
  },
  {
    id: "22",
    name: "New Science",
    provider: "Jaan Tallin & Vitalik",
    amount: "$157,000",
    deadline: "August 15, 2024",
    category: "Science",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Each fellow receives a stipend of $6,000 per month, as well as $5,000 per month for project costs and $25,000 in computational credits",
    eligibility: ["Scientific researchers", "Computational focus", "Long-term projects"],
    applicationLink: "https://newscience.org/",
    tags: ["Science", "Research", "Fellowship"]
  },
  {
    id: "23",
    name: "Next Generation Internet 0",
    provider: "NLnet Foundation",
    amount: "$5,000 - $50,000",
    deadline: "Rolling",
    category: "Technology",
    location: "Europe",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "We support projects that contribute to an open, resilient, trustworthy, sustainable and human-centered internet",
    eligibility: ["Open internet projects", "European focus", "Technical innovation"],
    applicationLink: "https://nlnet.nl/funding.html",
    tags: ["Internet", "Technology", "Europe"]
  },
  {
    id: "24",
    name: "Non Trivial",
    provider: "Peter McIntyre / Non-Trivial Ventures",
    amount: "$2,000 - $12,000",
    deadline: "Rolling",
    category: "Youth",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Enabling ambitious teenagers to start solving the world's most pressing problems",
    eligibility: ["Teenagers", "Ambitious projects", "Problem solvers"],
    applicationLink: "https://www.non-trivial.org/",
    tags: ["Youth", "Teenagers", "Impact"]
  },
  {
    id: "25",
    name: "O'Shaughnessy Fellowship",
    provider: "O'Shaughnessy Ventures",
    amount: "$100,000",
    deadline: "September 1, 2024",
    category: "Entrepreneurship",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "For ambitious people who want to build something great",
    eligibility: ["Ambitious builders", "Entrepreneurial mindset", "Great ideas"],
    applicationLink: "https://www.osv.llc/oshaughnessy-fellowships",
    tags: ["Entrepreneurship", "Fellowship", "Building"]
  },
  {
    id: "26",
    name: "O'Shaughnessy Grants",
    provider: "O'Shaughnessy Ventures",
    amount: "$10,000",
    deadline: "September 1, 2024",
    category: "Innovation",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "20 individuals will each receive $10k & access to OSV's network. Winners will be selected from their Fellowship Application",
    eligibility: ["Fellowship applicants", "Network access", "Innovative projects"],
    applicationLink: "https://www.osv.llc/oshaughnessy-fellowships",
    tags: ["Innovation", "Network", "Grants"]
  },
  {
    id: "27",
    name: "Promise Prize",
    provider: "Atrum",
    amount: "$250,000",
    deadline: "Contact team",
    category: "Prize",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Large prize for transformative projects. Email team@promiseprize.org",
    eligibility: ["Transformative projects", "High impact", "Contact for details"],
    applicationLink: "https://promiseprize.org",
    tags: ["Prize", "Large Grant", "Impact"]
  },
  {
    id: "28",
    name: "Protostars",
    provider: "Blackbird Foundation",
    amount: "$1,000",
    deadline: "Rolling",
    category: "Youth",
    location: "Australia/NZ",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "We're giving young people $1k for their passion projects! We're looking for the wildest hearts with the wildest ideas and projects",
    eligibility: ["Young people", "Australia/NZ", "Passion projects"],
    applicationLink: "https://www.blackbird.vc/programs/protostars",
    tags: ["Youth", "Australia", "Passion Projects"]
  },
  {
    id: "29",
    name: "Rainer Arnhold Fellowship",
    provider: "Mulago Foundation",
    amount: "$100,000",
    deadline: "October 1, 2024",
    category: "Poverty",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "We find leaders with promising poverty solutions and help them to design and deliver them at scale",
    eligibility: ["Poverty solutions", "Scalable impact", "Strong leadership"],
    applicationLink: "https://www.mulagofoundation.org/rainer-fellows-program",
    tags: ["Poverty", "Fellowship", "Impact"]
  },
  {
    id: "30",
    name: "Rise Program",
    provider: "Schmidt & Rhodes",
    amount: "Scholarships & Funding",
    deadline: "November 1, 2024",
    category: "Youth",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "The program starts at ages 15–17 and offers benefits including scholarships, mentorship, access to career development opportunities, funding, and more as Global Winners work toward solving humanity's most pressing problems",
    eligibility: ["Ages 15-17", "Problem solvers", "Global impact"],
    applicationLink: "https://www.risefortheworld.org/",
    tags: ["Youth", "Scholarship", "Mentorship"]
  },
  {
    id: "31",
    name: "Schmidt Futures",
    provider: "Schmidt Futures",
    amount: "Varies",
    deadline: "Various",
    category: "Technology",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Various programs supporting science and technology talent",
    eligibility: ["Tech/science focus", "Exceptional talent", "Multiple programs"],
    applicationLink: "https://www.schmidtfutures.com/",
    tags: ["Technology", "Science", "Multiple Programs"]
  },
  {
    id: "32",
    name: "SciFounder Fellowship",
    provider: "SciFounders",
    amount: "$400,000",
    deadline: "December 1, 2024",
    category: "Science Startups",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Help more technical teams run their own companies. At least one founder should have started working full-time for the company. Care most about the quality of the founders and try to be agnostic about ideas",
    eligibility: ["Technical founders", "Full-time commitment", "Science-based startups"],
    applicationLink: "https://www.janestreet.com/join-jane-street/programs-and-events/graduate-research-fellowship/",
    tags: ["Science", "Startups", "Fellowship"]
  },
  {
    id: "33",
    name: "Silicon Valley Fellowship",
    provider: "Gomry Next Gen Fund",
    amount: "$1,000 - $5,000",
    deadline: "Rolling",
    category: "Tech",
    location: "Silicon Valley",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "The SVF is a program to get fast-tracked into Silicon Valley through a community of experienced Silicon Valley mentors, talks & events in SV + online",
    eligibility: ["Tech builders", "Silicon Valley interest", "Mentorship-focused"],
    applicationLink: "https://www.siliconvalleyfellowship.com/",
    tags: ["Tech", "Silicon Valley", "Mentorship"]
  },
  {
    id: "34",
    name: "Telora",
    provider: "Telora",
    amount: "$40,000",
    deadline: "January 15, 2025",
    category: "Youth",
    location: "Miami",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Young people willing to move to Miami for 6 months",
    eligibility: ["Young people", "Relocate to Miami", "6-month commitment"],
    applicationLink: "https://telora.com/",
    tags: ["Youth", "Miami", "Relocation"]
  },
  {
    id: "35",
    name: "Thiel Fellowship",
    provider: "Thiel Foundation",
    amount: "$100,000",
    deadline: "Rolling",
    category: "Entrepreneurship",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "16 - 22 years old fellowship for young entrepreneurs leaving school to build something new",
    eligibility: ["Ages 16-22", "Leave school", "Build something new"],
    applicationLink: "https://thielfellowship.org/",
    tags: ["Entrepreneurship", "Youth", "Fellowship"]
  },
  {
    id: "36",
    name: "Vibefund",
    provider: "Vibecamp",
    amount: "$500+",
    deadline: "Rolling",
    category: "Community",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Financial support, networking, and counseling for members of the vibecamp community to help them make progress on creative, technical, and professional projects",
    eligibility: ["Vibecamp community", "Creative/technical projects", "Professional development"],
    applicationLink: "https://vibe.camp/vibefund/",
    tags: ["Community", "Creative", "Technical"]
  },
  {
    id: "37",
    name: "WTFund",
    provider: "WTF Podcast",
    amount: "~$25,000",
    deadline: "February 28, 2025",
    category: "Youth",
    location: "India",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "People 25 and under. Must be an Indian registered entity (they help with legal support for this too)",
    eligibility: ["25 and under", "India", "Registered entity"],
    applicationLink: "https://www.allthingswtf.com/wtfund",
    tags: ["Youth", "India", "Entrepreneurship"]
  },
  {
    id: "38",
    name: "Z Fellows",
    provider: "Cory Levy",
    amount: "$10,000",
    deadline: "Rolling",
    category: "Tech",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "We'll give you $10,000 to go all in on your project or idea for one week. Join a cohort of early technical thinkers and learn from some of Silicon Valley's smartest mentors",
    eligibility: ["Technical thinkers", "One week commitment", "All-in mindset"],
    applicationLink: "https://zfellows.com",
    tags: ["Tech", "Mentorship", "Intensive"]
  },
  {
    id: "39",
    name: "Local Host",
    provider: "KG Ventures",
    amount: "$1,000 - $100,000",
    deadline: "Rolling",
    category: "Youth",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Driven ambitious GenZ builders willing to go all-in on their ideas. Grants - $1-5k. Investments - up to $100k",
    eligibility: ["Gen Z", "All-in commitment", "Ambitious builders"],
    applicationLink: "https://offlocalhost.xyz/",
    tags: ["Gen Z", "Investments", "Grants"]
  },
  {
    id: "40",
    name: "Roddenberry Catalyst",
    provider: "Roddenberry Foundation",
    amount: "$2,500 - $15,000",
    deadline: "Rolling",
    category: "Social Impact",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Early Stage + Big Ideas + Bold Vision. Catalyst supports projects from anywhere in the world by individuals, teams, non-profits, or social enterprises",
    eligibility: ["Early stage", "Bold vision", "Social impact"],
    applicationLink: "https://roddenberryfoundation.org/our-work/catalyst-fund/",
    tags: ["Social Impact", "Early Stage", "Bold Ideas"]
  },
  {
    id: "41",
    name: "General Catalyst Venture Fellows",
    provider: "General Catalyst",
    amount: "$2,500",
    deadline: "Rolling",
    category: "Student Startups",
    location: "United States",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "We're here to help you get your company from first draft to final draft. If you're a student working on a startup, apply here to be considered for an investment from GC Venture Fellows! We only invest in student-run companies",
    eligibility: ["Students", "Startups", "US-based"],
    applicationLink: "https://www.generalcatalyst.com/venture-fellows",
    tags: ["Students", "Startups", "Venture"]
  },
  {
    id: "42",
    name: "Cactus Capital",
    provider: "Cactus Capital",
    amount: "$50 - $100",
    deadline: "Rolling",
    category: "Micro-grants",
    location: "United States",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "We're high schoolers from northern virginia looking to fund cool projects. We provide student builders with microgrants of $50-100 to help them get started. You can be at any stage with your project, it can even be just an idea you have. We don't want equity",
    eligibility: ["Students", "Any stage", "Cool projects"],
    applicationLink: "https://cactuscapital.org/",
    tags: ["Micro-grants", "Students", "Projects"]
  },
  {
    id: "43",
    name: "CryoDAO",
    provider: "CryoDAO",
    amount: "$100 - $3,000",
    deadline: "Rolling",
    category: "Cryopreservation",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "The CryoDAO Fellowship aims to empower individuals with need-based grants to become more deeply involved in the field of cryopreservation. These grants will support activities such as research, education, conference attendance, and joining relevant programs or fellowships",
    eligibility: ["Cryopreservation interest", "Need-based", "Research/education focus"],
    applicationLink: "https://www.cryodao.org/fellowship",
    tags: ["Cryopreservation", "Research", "Fellowship"]
  },
  {
    id: "44",
    name: "Go Human",
    provider: "Go Human! Fund",
    amount: "$100",
    deadline: "Rolling",
    category: "Micro-grants",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "We give smol checks to help young go! Building smth cool? Hit the dm's. We're here to help u go go go! :)",
    eligibility: ["Young builders", "Cool projects", "Just get started"],
    applicationLink: "http://gohuman.fund/",
    tags: ["Micro-grants", "Youth", "Quick"]
  },
  {
    id: "45",
    name: "Bagel Fund",
    provider: "Bagel Fund",
    amount: "$100 - $500",
    deadline: "Rolling",
    category: "Micro-grants",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Micro-grants for student builders and young creators",
    eligibility: ["Students", "Young creators", "Quick turnaround"],
    applicationLink: "https://bagel.fund",
    tags: ["Micro-grants", "Students", "Quick"]
  },
  {
    id: "46",
    name: "Merge Grant",
    provider: "Ari Dutilh & Julian Weisser",
    amount: "$50 - $1,000",
    deadline: "Rolling",
    category: "Projects",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Amplify and accelerate projects born out of goldilocks periods. We also wanted to try and kick off these goldilocks projects for people no matter their point in time",
    eligibility: ["Project-focused", "Any timing", "Acceleration-ready"],
    applicationLink: "https://odteam.notion.site/Merge-Grant-7eadfac121ae45328c80cd3a733fb2ab",
    tags: ["Projects", "Micro-grants", "Acceleration"]
  },
  {
    id: "47",
    name: "Polar Fellowship",
    provider: "Entrepreneur First",
    amount: "Project Funding",
    deadline: "March 1, 2025",
    category: "Fellowship",
    location: "UK (Oxford, Cambridge, London)",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Polaris is a 9 month programme built to give you and 24 other exceptional fellows an environment to think concretely about the path you want to take. Includes curated curriculum, project money, and thoughtful guidance",
    eligibility: ["High school to PhD", "UK-based or willing to attend", "9-month commitment"],
    applicationLink: "https://www.polaris-fellowship.com/",
    tags: ["Fellowship", "UK", "Projects"]
  },
  {
    id: "48",
    name: "Foundry",
    provider: "Blackbird",
    amount: "$1,000 - $5,000",
    deadline: "Rolling",
    category: "Research",
    location: "Australia/NZ",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Researchers with ties to Australia or NZ who want to learn about starting a company. 5k cash prize for winning team at the end of a cohort",
    eligibility: ["Australia/NZ ties", "Researchers", "Startup interest"],
    applicationLink: "https://www.blackbird.vc/foundry",
    tags: ["Research", "Australia", "Startups"]
  },
  {
    id: "49",
    name: "Breakthrough Energy Fellows",
    provider: "Bill Gates",
    amount: "$50,000 - $500,000",
    deadline: "April 30, 2025",
    category: "Climate",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Our flagship program, the Innovator Fellowship, is designed to accelerate the development of promising early-stage climate technologies",
    eligibility: ["Climate tech", "Early-stage", "Scalable solutions"],
    applicationLink: "https://befellows.smapply.org/",
    tags: ["Climate", "Technology", "Fellowship"]
  },
  {
    id: "50",
    name: "The Formidable Fund",
    provider: "Formidable Fund",
    amount: "$1,000",
    deadline: "November 22, 2024",
    category: "Youth",
    location: "United States",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "US middle and high school entrepreneurs. Permanent Residents & US citizens. Grants are given out on a rolling basis. Mention 1517 Fund as a referrer",
    eligibility: ["Middle/high school", "US citizens/residents", "Entrepreneurs"],
    applicationLink: "https://www.formidablefund.org/",
    tags: ["Youth", "Students", "Entrepreneurship"]
  },
  {
    id: "51",
    name: "Young Builders Society",
    provider: "evm.capital",
    amount: "$100 - $600",
    deadline: "Rolling",
    category: "Youth",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Give ambitious builders under the age of 23 the financial boost they need to bring their ideas to life, with a strong focus on originality, impact, and practicality",
    eligibility: ["Under 23", "Original ideas", "Practical projects"],
    applicationLink: "https://www.youngbuildersociety.com/",
    tags: ["Youth", "Builders", "Micro-grants"]
  },
  {
    id: "52",
    name: "Lift Off Grant",
    provider: "Exerton, Jake O'Shea",
    amount: "$50 - $100",
    deadline: "Rolling",
    category: "Youth",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Anyone 18 years old or younger / Any type of project - from art to technology / No prior experience required / Located anywhere in the world",
    eligibility: ["18 and under", "Any project type", "Global"],
    applicationLink: "https://www.liftoffgrant.com/",
    tags: ["Youth", "Micro-grants", "Beginner-friendly"]
  },
  {
    id: "53",
    name: "The Flight School",
    provider: "The Flight School",
    amount: "$10,000",
    deadline: "Various cohorts",
    category: "Gap Year",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Re-inventing the 'gap year' as an accessible, aspirational and rebellious rite of passage",
    eligibility: ["Gap year students", "Aspirational thinkers", "Alternative education"],
    applicationLink: "https://theflightschool.org/",
    tags: ["Gap Year", "Education", "Alternative"]
  },
  {
    id: "54",
    name: "Manifest Grants",
    provider: "Fifty Years",
    amount: "$25,000 - $100,000",
    deadline: "May 15, 2025",
    category: "Innovation",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Large grants for ambitious innovators working on transformative projects",
    eligibility: ["Transformative projects", "Ambitious scope", "Clear vision"],
    applicationLink: "https://www.fiftyyears.com/manifest",
    tags: ["Innovation", "Large Grants", "Transformative"]
  },
  {
    id: "55",
    name: "Astera Residency Program",
    provider: "Astera Institute",
    amount: "$125,000 - $250,000",
    deadline: "June 30, 2025",
    category: "Science",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Provide talented people freedom and support to create new machinery of science",
    eligibility: ["Scientific innovators", "Machinery of science", "Research freedom"],
    applicationLink: "https://astera.org/residency/",
    tags: ["Science", "Residency", "Large Grants"]
  },
  {
    id: "56",
    name: "Da Vinci Fellowship",
    provider: "Da Vinci Fellowship",
    amount: "€150,000",
    deadline: "July 31, 2025",
    category: "Youth",
    location: "Europe",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Under 25, ambitious young builders in Europe who have demonstrated exceptional ability in any field",
    eligibility: ["Under 25", "Europe-based", "Exceptional ability"],
    applicationLink: "https://davincifellowship.com",
    tags: ["Youth", "Europe", "Fellowship"]
  },
  {
    id: "57",
    name: "Techyon Microgrants",
    provider: "Hack the North",
    amount: "$1,000 - $2,000",
    deadline: "June 30, 2025",
    category: "Students",
    location: "Canada",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "10 students / Canada / before June 30, 2025 / student at a Canadian college or university / to give students real support for cool projects",
    eligibility: ["Canadian students", "College/university", "Cool projects"],
    applicationLink: "https://microgrants.hackthenorth.com/",
    tags: ["Students", "Canada", "Micro-grants"]
  },
  {
    id: "58",
    name: "Sawa Grant",
    provider: "Sawa",
    amount: "$500",
    deadline: "Rolling",
    category: "Youth",
    location: "Global",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Sawa is a microgrant fund for young builders creating public-facing projects that make a real impact in their communities. Whether you're building your first robot, launching a SaaS, or creating a design studio, we'll help get you off the ground",
    eligibility: ["Young builders", "Public-facing", "Community impact"],
    applicationLink: "https://grants.sawa.fm/",
    tags: ["Youth", "Community", "Micro-grants"]
  },
  {
    id: "59",
    name: "Stochastic Labs Summer Residency",
    provider: "Stochastic Labs",
    amount: "Residency + Travel",
    deadline: "May 1, 2025",
    category: "Research",
    location: "United States",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "July 8th - September 15th. There's a lot of emphasis right now on 'frontier models' with the race to AGI taking center stage, but there are emergent, overlooked, abandoned, barely perceptible or even hidden-in-plain-sight opportunities. Includes accommodation + travel",
    eligibility: ["Research focus", "Summer availability", "Exploratory mindset"],
    applicationLink: "http://bit.ly/stochasticlabs2025",
    tags: ["Research", "Residency", "Summer"]
  },
  {
    id: "60",
    name: "Greenhorn Microgrants",
    provider: "Greenhorn Innovation Fund",
    amount: "$100 - $500",
    deadline: "Rolling",
    category: "STEM",
    location: "United States",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    description: "Giving microgrants to young students to work on their own STEM projects / 501c3",
    eligibility: ["Young students", "STEM projects", "US-based"],
    applicationLink: "https://greenhorninnovationfund.org/",
    tags: ["STEM", "Students", "Micro-grants"]
  }
];